name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Sync Fork
        run: |
          git remote add upstream ${{ github.event.repository.parent.html_url }}
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main